languageCode = "en-us"

baseURL             = "http://homeonrails.com/"
copyright           = "All rights reserved - 2017"
paginate            = 5
pluralizeListTitles = false
theme               = "casper"
title               = "Home on Rails"
canonifyurls        = true

disqusshortname    = "homeonrails"

[permalinks]
  post = "/:year/:month/:slug/"

[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/"
  weight     = -120

[[menu.main]]
  name = "About me"
  weight = -119
  identifier = "about"
  url = "/about"

[[menu.main]]
  name   = "Most popular posts"
  pre    = "<h3>Explore</h3>"
  url    = "/most-popular-posts"
  weight = 100

[[menu.main]]
  name   = "Talks"
  url    = "https://speakerdeck.com/melekes"
  weight = 101

[[menu.main]]
  name   = "Github repos"
  pre    = "<h3>Follow Me</h3>"
  url    = "https://github.com/melekes"
  weight = 110

[[menu.main]]
  name   = "Twitter timeline"
  url    = "https://twitter.com/akaliaev"
  weight = 111

[[menu.main]]
  name   = "LinkedIn"
  pre    = "<h3>Contact Me</h3>"
  url    = "http://www.linkedin.com/in/melekes"
  weight = 120

[[menu.main]]
  name = "Keybase (secure msg)"
  url = "https://Keybase.io/melekes"
  weight = 121

[params]
  author                = "Anton Kaliaev"
  authorlocation        = "Ulyanovsk, Russia"
  authorwebsite         = "http://homeonrails.com"
  bio                   = "Software engineer, blogger, public speaker, traveler"
  cover                 = "images/cover.png"
  description           = "Magic unicorns, steep rabbits, fat cats discussing software development"
  githubName            = "melekes"
  googleAnalyticsUserID = "UA-35080566-1"
  hideHUGOSupport       = false
  logo                  = "images/logo.png"
  twitterName           = "akaliaev"
  customHeaderPartial   = "header.include.html"

[sitemap]
  ChangeFreq = ""
  Filename   = "sitemap.xml"
  Priority   = "-1"
